### ISSUE TITLE
more modern monospace font

### ISSUE THREAD

**Issue by williamspatrick** [derick-montague/openbmc-styleguide-proposal#1]
https://github.com/derick-montague/openbmc-styleguide-proposal/blob/master/src/styles/typography.njk#L137

Most of the uses of monospace font within the openbmc web interface are presenting very "terminal-like" data.  The Courier family is good because it is universal, but it isn't considered a great font for terminal work because it can be difficult to read compared to other fonts.  Can we explore a more modern font, such as the Menlo / DejuVu / Bitstream Vera Sans Mono family?  While none of them are universal on their own, I think if you specify all 3 you'll get coverage on MacOS / Windows / Linux respectively (and all 3 are nearly identical fonts).

**Comment by derick-montague** [comment]
We can definitely look into an update for that. Thank you for contributing and offering your feedback. This is not an official style guide, but this is exactly what I was hoping it would be used for! I am in the process of putting together more info to send to the OpenBMC community about the value that a style guide would offer.

**Comment by derick-montague** [comment]
SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace is the font-stack that bootstrap 4 is using. I have been reading some articles and this seems like it should hit all the systems. I did read somewhere that Ubuntu users might want Ubuntu Monospace added.

**Comment by williamspatrick** [comment]
Sounds good @derick-montague.  That would satisfy me. Thank you!
